package ui

import (
	"bytes"
	"fmt"

	"github.com/charmbracelet/lipgloss"
)

var (
	// Brutalist palette: Dark gray border, bright white text.
	borderStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("8")).Bold(true)
	textStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("15"))
	successStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("2")).Bold(true) // Green
	infoStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("6")).Bold(true) // Cyan
)

// LogStream implements io.Writer. It intercepts raw terminal output and formats it.
type LogStream struct{}

// Write processes the byte stream from the executed command in real-time.
func (s *LogStream) Write(p []byte) (n int, err error) {
	// Split the incoming chunk by newlines to format each line cleanly
	lines := bytes.Split(p, []byte("\n"))
	
	for i, line := range lines {
		// Drop trailing empty lines generated by byte splits
		if i == len(lines)-1 && len(line) == 0 {
			continue
		}
		// Render the clean, vertical border next to the raw output
		fmt.Printf("%s %s\n", borderStyle.Render("│"), textStyle.Render(string(line)))
	}
	
	return len(p), nil
}

// PrintStep renders a cleanly formatted system message (e.g., "Resolving package...").
func PrintStep(msg string) {
	fmt.Printf("%s %s\n", infoStyle.Render("::"), textStyle.Render(msg))
}

// PrintSuccess renders the final completion message.
func PrintSuccess(msg string) {
	fmt.Printf("%s %s\n", successStyle.Render("✔"), textStyle.Render(msg))
}